### ISSUE TITLE
Function Reference injection doesn't work unless provided type is specified explicitly

### ISSUE THREAD

**Issue by dellisd** [evant/kotlin-inject#125]
If I want to inject a function reference into a class, the build fails unless I explicitly specify the provided type for the function reference in the component. Without the return type, it defaults to the behaviour of trying to generate a provider and in the following example complains that `Any` can't be provided.

i.e.   
this does not work:
```kotlin
@Inject
class MyClass(private val myProvider: suspend () -> Any)

suspend fun theProvider(): Any { /* ... */ }

@Component
abstract class AppComponent {
  @Provides
  protected fun provideTheProvider() = ::theProvider
}
```

but this does:
```kotlin
@Inject
class MyClass(private val myProvider: suspend () -> Any)

suspend fun theProvider(): Any { /* ... */ }

@Component
abstract class AppComponent {
  @Provides
  protected fun provideTheProvider(): suspend () -> Any = ::theProvider
}
```

I'm not sure if this is intended behaviour or not, but if it is then it might be worth documenting.

**Comment by evant** [comment]
It's likely this is a bug, what backend are you using? kapt or ksp?

**Comment by evant** [comment]
Ah, it's because the type of `::theProvider` is `KSuspendFunction0<Any>` which is _different_ from `suspend () -> Any` which has type `Function1<Any, Continuation>`. Will have to think about if we want to special-case this.

Note: a similar thing happens without `suspend` as well. The method reference has type `KFunction0<Any>` while `() -> Any` is type `Function0<Any>`

**Comment by evant** [comment]
I'm leaning towards yes we should as `KSuspendFunction0`/`KFunction0` appear to be 'special' types that you can't declare yourself so it's impossible to match them.

**Comment by evant** [comment]
Note: this isn't the [first issue](https://github.com/evant/kotlin-inject/issues/110) I've run into with implicit `@Provides` return types. I think I'm going to add a recommendation that **you always explicitly declare the `@Provides` return type**. It seems like often-times it's not the type you expect it to be.

**Comment by dellisd** [comment]
I figured it would probably be because of something like that. I tried it out with some other frameworks (Koin and Dagger) and neither of them were able to handle it and they also showed errors relating to a `Function` type.

Making a note of explicitly specifying the return type in the documentation would be useful.
