### ISSUE TITLE
Runtime annotation retention causes warning in JS targets

### ISSUE THREAD

**Issue by dellisd** [evant/kotlin-inject#181]
All of the annotations in the runtime library are marked with `@Retention(RUNTIME)`. It's not immediately obvious to me what purpose this serves since my understanding is that they're only used at compile time(?), but either way; using these annotations in a JS sourceset produces the following warning:

`Reflection is not supported in JavaScript target, therefore you won't be able to read this annotation in run-time`

Ideally it would produce no warnings.

Happy to open a PR to change the retention annotations, but just wanted to open a discussion first.

**Comment by evant** [comment]
The reason for this is cases where you'd want to detect them on the jvm. I agree the warning is useless and annoying on js. https://youtrack.jetbrains.com/issue/KT-41082.

I'd be open to changes to fix this that don't affect the jvm behavior if you know of a way.

**Comment by dellisd** [comment]
I tried to use `expect`/`actual` with different retention annotations for the `actual` declarations, but unsurprisingly it didn't work.
Out of ideas for now.

**Comment by evant** [comment]
Actually it looks like retention annotation may be removed all together (see https://github.com/Kotlin/kotlinx.serialization/commit/317cbf94785c703e5315081d9baa0a385f577145). I had wrongly assumed class was the default retention like it is in java.
