### ISSUE TITLE
multiplatform support kotlin 1.6.20

### ISSUE THREAD

**Issue by NicolaVerbeeck** [evant/kotlin-inject#193]
It seems that the configuration suggested in #1 does not work with kotlin 1.6.2(0/1) anymore. Any pointers on getting this working again?

**Comment by NicolaVerbeeck** [comment]
https://github.com/google/ksp/releases/tag/1.6.20-M1-1.0.2 Mentions something about it but I could not get it to work

**Comment by NicolaVerbeeck** [comment]
Seems I figured it out :D 

```kotlin
dependencies {
    add("kspCommonMainMetadata", "me.tatarka.inject:kotlin-inject-compiler-ksp:0.4.1")
}

kotlin.sourceSets.commonMain {
    kotlin.srcDir("build/generated/ksp/metadata/commonMain/kotlin")
}
tasks.withType<org.jetbrains.kotlin.gradle.dsl.KotlinCompile<*>>().all {
    if (name != "kspCommonMainKotlinMetadata") {
        dependsOn("kspCommonMainKotlinMetadata")
    }
    kotlinOptions.freeCompilerArgs = listOf("-opt-in=kotlin.RequiresOptIn")
}
```

**Comment by evant** [comment]
@NicolaVerbeeck I tried to update the sample but I'm getting
```
Task with path 'kspCommonMainKotlinMetadata' not found in root project 'echo'.
```
is there something I'm missing?

**Comment by NicolaVerbeeck** [comment]
What version did you update ksp to?

**Comment by evant** [comment]
1.6.21-1.0.5

**Comment by eygraber** [comment]
@evant it should be working here https://github.com/evant/kotlin-inject/pull/195/files#diff-b6c60f550f51363eb9ea6e7e05fa7fd89f4ce64989ab6d6fbf650755ccefa366R28

**Comment by NicolaVerbeeck** [comment]
@evant what @eygraber shows should indeed work

**Comment by evant** [comment]
Right good point, will take a closer look

**Comment by eygraber** [comment]
I ended up modifying it a little bit in my project:

```kotlin
val kotlin = extensions["kotlin"]
if(kotlin is KotlinMultiplatformExtension) {
  kotlin.targets.configureEach {
    configureKsp()
  }
}

fun KotlinTarget.configureKsp() {
  if(targetName != "metadata") {
    dependencies {
      add("ksp${targetName.capitalize()}", libs.kotlinInject.compiler)
    }
  }

  compilations.configureEach {
    kotlinSourceSets.forEach { sourceSet ->
      sourceSet.kotlin.srcDir("build/generated/ksp/$targetName/${sourceSet.name}/kotlin")
    }
  }
}
```

**Comment by jagtejsodhi** [comment]
Hey folks, I'm on Kotlin 1.8.20 and seeing an issue even after trying @eygraber's workaround.

The code is only generating for jvmMain, and no other source set.

This is my gradle setup:

```
plugins {
  `opensea-kmm-ios-module`
  `opensea-kmm-jvm-module`
  `opensea-kmm-impl-module`
  alias(libs.plugins.ksp)
}

kotlin {
  sourceSets {
    val commonMain by getting {
      dependencies {
        implementation(libs.kotlinInjectRuntime)
      }
    }
  }
}

val kotlin = extensions["kotlin"]
if(kotlin is org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension) {
  kotlin.targets.configureEach {
    configureKsp()
  }
}

fun KotlinTarget.configureKsp() {
  if(targetName != "metadata") {
    dependencies {
      add("ksp${targetName.capitalize()}", libs.kotlinInjectCompilerKsp)
    }
  }

  compilations.configureEach {
    kotlinSourceSets.forEach { sourceSet ->
      sourceSet.kotlin.srcDir("build/generated/ksp/$targetName/${sourceSet.name}/kotlin")
    }
  }
}
```

And here is the generated code:
<img width="538" alt="Screenshot 2023-07-14 at 2 17 24 PM" src="https://github.com/evant/kotlin-inject/assets/10988161/424b7660-e464-416c-b27f-3d14c18b2025">


Any suggestions?

**Comment by eygraber** [comment]
See if there's anything here that helps - https://github.com/eygraber/gradle-conventions/blob/master/conventions-plugin/src/main/kotlin/ksp.kt

**Comment by evant** [comment]
Going to close this out since a lot of the advice here is now out of date. I would recommend looking at the [multiplatform greeter sample](https://github.com/evant/kotlin-inject-samples/tree/main/multiplatform/greeter) these days to get something working.
