### ISSUE TITLE
update samples to include the latest way to do multiplatform codegen for ios & android

### ISSUE THREAD

**Issue by idrisadetunmbi** [evant/kotlin-inject#236]
I am trying to use this library in a Kotlin multiplatform mobile project, and while I can find the tasks that generate the `ksp` build package in the android module, I can't find the same in other modules. Can't find samples in the project for this as well.

My main ask is to be able to generate the component `create` method in the `shared` module so I can call the method to initialize my component on the iOS side.

Thanks.

**Comment by jstarczewski** [comment]
Hi @idrisadetunmbi I'am also working on KMM apps using this library and we are basically creating components in shared module. I created w very simple sample project [here](https://github.com/jstarczewski/kotlin-inject-kmm-example) where you can see how it [works](https://github.com/jstarczewski/kotlin-inject-kmm-example/blob/main/shared/src/commonMain/kotlin/com/jstarczewski/kotlininjectkmm/ExampleComponent.kt). Hope it helps, the only thing you probably have to do is **to clean the build when switching from Android to iOS build** as there are some already generated files resulting in conflict between compilation target switch. 

Let me know whether it helps to solve you problem :)
