### ISSUE TITLE
Warn when scope annoation would have no effect

### ISSUE THREAD

**Issue by denchic45** [evant/kotlin-inject#238]
If I pass the dependency through the provide function using scope, then everything works correctly:
```
    @MyScope
    @Provides
    fun provideFoo() = Foo()
```
generation:
```
foo = _scoped.get("com.example.Foo") {
        provideFoo()
      }
```
But if I declare a variable instead, then the scope is ignored:
```
    @MyScope
    abstract val foo: Foo
```
generation:
```
  public override val foo: Foo
    get() = Foo()
```
or:
```
    @MyScope
    abstract val lambdaFoo: () -> Foo
```
generation:
```
  public override val lambdaFoo: Function0<Foo>
    get() = {
      Foo()
    }
```

**Comment by evant** [comment]
Try @get:MyScope

**Comment by denchic45** [comment]
doesn't seem to help
```
    @get:AppScope
    abstract val foo: Foo
```

```
  public override val foo: Foo
    get() = Foo()
```

**Comment by evant** [comment]
Oh sorry missed what you are doing. Scope annotations go on `@Provides` methods or on the class to inject. You are putting it on the generated component method. Probably could produce a helpful error message for this.

**Comment by denchic45** [comment]
Yes, I think it makes sense to ban such cases

**Comment by evant** [comment]
This is now partially addressed. Due to a limitation with the KAPT back-end it will miss cases where the property is annotated itself instead of it's getter. ex: `@MyScope abstract val myProp` is missed but
`@get:MyScope abstract val myProp` is caught. This can be improved once the KAPT back-end is removed.

**Comment by sergeshustoff** [comment]
@evant looks like it can be closed - warning shows when property is annotated. Pr isn't marked as closing it because it technically doesn't... Maybe I should've just mark it there
