### ISSUE TITLE
Generated code adds generics bounds to type aliases when it shouldn't

### ISSUE THREAD

**Issue by tunjid** [evant/kotlin-inject#239]
I have the following typealias:

```
typealias NavMutator = ActionStateProducer<NavMutation, StateFlow<NavState>>
```

In my generated code, I get the following:

```
public class InjectAppScreenStateHolderComponent(
  archiveListComponent: ArchiveListScreenHolderComponent
) : AppScreenStateHolderComponent(archiveListComponent) {
  private val _navMutator: NavMutator<NavMutation<NavContext, MultiStackNav>, StateFlow<NavState>>
```

The code above does not compile as the `NavMutator` typealias does expect type arguments.

**Comment by evant** [comment]
I'm having trouble reproducing this, if you are still having this issue can you post a sample component that generates the invalid code?

**Comment by tunjid** [comment]
This was a while ago, I don't have the reproduction code anymore. Will reopen if I run into it again.
