### ISSUE TITLE
Multi-bindings does not work with type aliases

### ISSUE THREAD

**Issue by leandrofavarin** [evant/kotlin-inject#240]
Suppose I have a component such as:
```kotlin
@Component
abstract class MyComponent {
  @Provides @IntoSet fun integer(): Int = 1
  @Provides @IntoSet fun myNumber(): MyNumber = 2

  abstract val integerSet: Set<Int>
  abstract val myNumberSet: Set<MyNumber>
}
```

Executing the following
```kotlin
with(MyComponent::class.create()) {
  println("Contents of integer set: $integerSet")
  println("Contents of myNumber set: $myNumberSet")
}
```

prints
```
Contents of integer set: [1]
Contents of myNumber set: [1]
```

Ideally `typealias` would allow generating another multibindings on the graph. 

Use case: Having different set of Interceptors for OkHttp (regular and Network types).

**Comment by senk0n** [comment]
Also doesn't work when trying to shorten `Map` declaration with type alias like:
```kotlin
typealias ProviderMap<P, R> = Map<ClassKey, DepProvider<P, R>>
```
this cause compile error `Cannot find an @Inject constructor or provider for *typealias*`
<details>
<summary>full setup I'm trying to use</summary>

```kotlin
typealias ClassKey = String
typealias ProviderMap<P, R> = Map<ClassKey, DepProvider<P, R>>

interface MultibindingFactory<in K : Any, out R : Any> {
    val providerMap: ProviderMap<K, R> // instead of Map<ClassKey, DepProvider<K, R>> which works fine
    fun create(key: K): R? {
        val provider = providerMap[key::class.qualifiedName]
        return provider?.provide(key)
    }
}

fun interface DepProvider<in P, out R> {
    fun provide(parameter: P): R
}
```
</details>

**Comment by evant** [comment]
Note: https://github.com/evant/kotlin-inject/issues/253 may make these resolve to the same thing in the future and they will need to be qualified in a different way but the current behavior completely ignores `@IntoSet` declarations that return a typealias so it's still worth fixing short-term
