### ISSUE TITLE
Unnecessary naming clash prevention when assisted injected dependencies are used in multi-binding

### ISSUE THREAD

**Issue by tfcporciuncula** [evant/kotlin-inject#250]
This isn't an important issue but just something I noticed in my journey trying to repro [this](https://github.com/evant/kotlin-inject/issues/244#issuecomment-1412594103), so feel free to close it if you don't think it's worth the fix!

Given this:

```kotlin
@Component
abstract class MainActivityComponent(
) {
  abstract val intSet: Set<Int>

  @Provides @IntoSet
  fun provideInt1(dep1: (String) -> Dep1) = 1

  @Provides @IntoSet
  fun provideInt2(dep2: (String) -> Dep2) = 2
}

@Inject class Dep1(@Assisted string: String)
@Inject class Dep2(@Assisted string: String)
```

We get this:

```kotlin
public class InjectMainActivityComponent() : MainActivityComponent() {
  public override val intSet: Set<Int>
    get() = setOf(
      provideInt1(
        dep1 = { arg0 ->
          Dep1(
            string = arg0
          )
        }
      ),
      provideInt2(
        dep2 = { arg0_ -> // No need for the _ here
          Dep2(
            string = arg0_
          )
        }
      )
    )
}
```

In our project we have plenty of that so it's a bit funny how far the `_` goes, but this doesn't really cause any issues right now.

**Comment by evant** [comment]
Yeah this could be improved. It has to do with the variable namer. Right now it just gets reset between each generated method. The 'right' way to do it would be to push and pop the state as you go down the graph so that siblings aren't part of the same state.
