### ISSUE TITLE
Assisted injection + scoped dependency cache one instance forever

### ISSUE THREAD

**Issue by dimsuz** [evant/kotlin-inject#262]
If I have something like this set up:

```kotlin
@CarScope
@Component
abstract class CarComponent {
  abstract val carRegistry: (districtId: String) -> CarRegistry
}

@CarScope
@Inject
class CarRegistry(@Assisted districtId: String)

fun main() {
  val component = CarComponent::class.create()
  val r1 = component.carRegistry("1")
  val r2 = component.carRegistry("2")

  r1 == r2 // -> true
}
```

From what I see in currently generated code for this setup, repeatedly calling `carRegistry` factory with different arguments will return a same instance each time, because the code looks this:

```kotlin
public override val carRegistry: Function1<String, CarRegistry>
  get() = { arg0 ->
    _scoped.get("com.example.CarRegistry") {
      CarRegistry(
        arg = arg0
      )
    }
  }
```

I would expect this to be implemented in such a way so that `LazyMap` key would include assisted args somehow, and so that calling with same args always would produce the same instance.

I'm not sure if this feature of having scoping based on assisted args makes sense and also not quite sure how Dagger would work in this case, but at least having current behavior looks a bit strange, perhaps a warning or an error should be given?

**Comment by evant** [comment]
Yeah agree that the current behavior is surprising, looks like [dagger](https://dagger.dev/dev-guide/assisted-injection.html#comparison-to-inject) simply disallows this which seems the simplest thing to do. While having the arg be part of the cache would be interesting, would be concerned about the fact that it's an unbounded cache so it would be easy to leak memory here.
