### ISSUE TITLE
[Help] Assisted inject guidance.

### ISSUE THREAD

**Issue by walter-whytied** [evant/kotlin-inject#265]
Hey folks. First of, kudos for this. I tried out kotlin-inject on a multiplatform project and it was not so hard to get things running. I however seem to have hit a roadblock on how to use assisted Inject. I hope you can guide me on how to go about it.

Some context:
I have a class `GithubList` that has a list of repositories. When I click on a list I need to pass the Id to `GithubDetailStateMachine`, class that has access to my repository and the Id to fetch the detail of the repo. How can I use @Assisted inject for the id?

``` kotlin
@Inject
class GithubDetailStateMachine(
    @Assisted private val id : Int,
    private val repository: GithubRepository
) : FlowReduxStateMachine() { ... }
```

My previous implementation looked something like this but I want to improve it and get rid of the `MutableStateFlow` object and use @Assisted like above.

``` kotlin
@Inject
class GithubDetailStateMachine(
    private val repository: GithubRepository
) : FlowReduxStateMachine() { 
     private var repoId: MutableStateFlow<Long> = MutableStateFlow(0)

    override fun handleAction(action: DetailAction) {
        when(action) {
            is RepoClicked -> {
                repoId.value = action.repoId //set the id.
                repository.fetchDetails(action.repoId){ .... }
            }
        }
    }

     suspend fun observeDetailsChanges() {
          repository.observeDeatils(repoId.value).collect {
           ....
          }
     }
 }
```

I would really appriciate some guidance.

**Comment by evant** [comment]
Could you explain exactly what your issue is? https://github.com/evant/kotlin-inject#function-support--assisted-injection has an example of how to do assisted injection. Is there something you tried and hit a roadblock?

**Comment by walter-whytied** [comment]
@evant I did try it. This is the error I am getting. 

```
e: [ksp] Mismatched @Assisted parameters.
Expected: [id: Long]
But got:  []
```

``` kotlin
@Inject
class RepoData(
    @Assisted val id: Long
)
```

**Comment by evant** [comment]
```kotlin
 private val repoData : (Int) -> RepoData
```
You need to specify a lamda so it can actually take the assisted argument

**Comment by walter-whytied** [comment]
I'm sorry I did not post this but I do have the labmda different class. 

``` kotlin
@Inject
class GithubRepoListStateMachine(
    private val repoData : (Int) -> RepoData
    private val repository: GithubRepository
) : FlowReduxStateMachine() { 
         
      init {
          repoData(23)
     }
 }
```

@Inject
class GithubDetailStateMachine(
    private val repoData : RepoData,
    private val repository: GithubRepository
) : FlowReduxStateMachine() { 
 
    fun useRepoID(){
           repository.getDetails(repodata.id)
    }

}

**Comment by evant** [comment]
You need the lambda in all cases. Otherwise how would it know what the assisted parm should be?

**Comment by walter-whytied** [comment]
Okay, I seem to have made some progresh. The final bit I'm stuck at is how to use id from`RepoData`. If I remove it from `GithubDetailStateMachine` the app compiles. 

``` kotlin
@Inject
class GithubDetailStateMachine(
    private val repoData : (Int) -> RepoData,
    // private val repoData : RepoData, // Without this it compiles but I need the id. 
    private val repository: GithubRepository
) : FlowReduxStateMachine() { 
 
    fun useRepoID(){
           //repository.getDetails(repodata.id)
    }
}
```
