### ISSUE TITLE
Generated code may refer to code requiring opt-in, failing compilation

### ISSUE THREAD

**Issue by damianw** [evant/kotlin-inject#267]
Components which either contain opt-in dependencies or are themselves annotated with an opt-in annotation (or `OptIn`) lead to generated code which will not compile, even if the component declaration or its containing file has opted in.

For example, this code:

```kotlin
@RequiresOptIn
annotation class SpecialApi

@Inject
@SpecialApi
class Dep

@Component
@OptIn(SpecialApi::class)
interface SomeComponent  {

    val dep: Dep
}
```

Would generate only:
```kotlin
public fun KClass<SomeComponent>.create(): SomeComponent = InjectSomeComponent()

public class InjectSomeComponent : SomeComponent {
  public override val dep: Dep
    get() = Dep()
}
```

This fails to compile because there is no opt-in for `SpecialApi` in the generated file. It is one example, but the same thing can happen for components being annotated, or for their supertypes, and so forth.

This problem was also discussed for Anvil in square/anvil#488, and the resolution there was to [add suppressions in the generated code](https://github.com/square/anvil/commit/fecfa9fcdf6673d87e8ae717790ae6ff4d026df0), which seems like it would also be a suitable solution for kotlin-inject.

**Comment by evant** [comment]
I've attempted to fix this but it seems like the suppress is being ignored? Branch [here](https://github.com/evant/kotlin-inject/pull/new/bugfix/opt-in) if anyone wants to take a look.

**Comment by evant** [comment]
Gave up on trying to suppress and decided to copy over the annotations instead, at least for file and class level opt-ins.
