### ISSUE TITLE
Annotation based multiple bindings support?

### ISSUE THREAD

**Issue by wsxyeah** [evant/kotlin-inject#282]
Annotation based multiple bindings is generally supported in popular DI frameworks. We can just use `@Named`, `@Qualifer` to represent the binding.

Currently with `kotlin-inject`, to provide a named binding, we have to return a `Pair` object. 
Any plan to support annotation based binding?

**Comment by evant** [comment]
Can you give an example on what exactly you are thinking and how it might be useful? The reason for the current implementation vs dagger's [multi-bindings](https://dagger.dev/dev-guide/multibindings.html#map-multibindings) is that a whole bunch of machinery doesn't need to be built to support keys at compile-time.

**Comment by wsxyeah** [comment]
Yes, javax inject is exactly what I need.
Thanks.

**Comment by evant** [comment]
Closing as a duplicate of #253 as that include a potential implementation of qualifiers
