### ISSUE TITLE
Cannot apply scope: @ActivityScope to type with @Assisted parameters

### ISSUE THREAD

**Issue by nesyou01** [evant/kotlin-inject#301]
KSP throws this issue
```
e: [ksp] Cannot apply scope: @ActivityScope to type with @Assisted parameters:
 [navigator: com.slack.circuit.runtime.Navigator]
```
This happens only in the new update 0.6.2.

Code:

```
@Inject
class Presenter(
    @Assisted private val navigator: Navigator
) : Presenter<Example> {
    @Composable
    override fun present(): State {}
}
```
```
@Inject
class PresenterFactory(
    private val presenter: (Navigator) -> Presenter,
) : Presenter.Factory {
    override fun create(
        screen: Screen,
        navigator: Navigator,
        context: CircuitContext
    ): Presenter<*>? = when (screen) {
        is HomeScreen -> presenter(navigator)
        else -> null
    }

}

```

**Comment by tfcporciuncula** [comment]
I'm having a similar issue but it only happens on the iOS build. Android build is fine, as all my dependencies with assisted args have no scope. But the iOS build fails with that message for some reason.

I'm trying to create a minimum reproducible example, but no luck so far.

**Comment by chrisbanes** [comment]
I'm seeing this in Tivi too ([here](https://github.com/chrisbanes/tivi/pull/1489)). I think the detection here might be a tad aggressive.

In Tivi, the issues I'm having are at the final stage where I need to publish a type which uses assisted injection underneath. For example, `TiviWorkerFactory` uses an assisted inject lambda underneath, but I need to access it somehow:

``` kotlin
@Component
@ApplicationScope
abstract class AndroidApplicationComponent(
    @get:Provides val application: Application,
) {
    abstract val workerFactory: TiviWorkerFactory
}
```

I tried making the type `() -> TiviWorkerFactory` to avoid scoping but that didn't work either.

**Comment by evant** [comment]
Sorry about that, turns out it was checking the completely wrong scope annotation. (The one on the component instead of the one on the constructor/provides method).

**Comment by evant** [comment]
@muhrifqii the change to prevent using assisted parameters on something scoped was intentional. See the note in the [release notes](https://github.com/evant/kotlin-inject/releases/tag/v0.6.2), and https://github.com/evant/kotlin-inject/issues/262. This bug was about the error incorrectly being triggered when it shouldn't have been.
