### ISSUE TITLE
Map multi-bindings don't support lambdas nor `Lazy`

### ISSUE THREAD

**Issue by vRallev** [evant/kotlin-inject#318]
This is similar to #242. Given
```kotlin
interface MyComponent {
    @Provides
    @IntoMap
    fun provideInt(): Pair<KClass<out Number>, Number> = Int::class to 1

    @Provides
    @IntoMap
    fun provideDouble(): Pair<KClass<out Number>, Number> = Double::class to 1.0

    val numbersEagerly: Map<KClass<out Number>, Number>
    val numbersLazy: Map<KClass<out Number>, Lazy<Number>>
    val numbersDelayed: Map<KClass<out Number>, () -> Number>
}
```
I'd expect this to compile and function accordingly. However, `numbersLazy` fails with
```
e: [ksp] Cannot find an @Inject constructor or provider for: Map<kotlin.reflect.KClass<out kotlin.Number>, kotlin.Lazy<kotlin.Number>>
```
and `numbersDelayed` with
```
e: [ksp] Cannot find an @Inject constructor or provider for: Map<kotlin.reflect.KClass<out kotlin.Number>, kotlin.Function0<kotlin.Number>>
```

For what it's worth, Dagger supports these options.

**Comment by evant** [comment]
You can make the value type a lambda or lazy to get this to work

```kotlin
interface MyComponent {
    @Provides
    @IntoMap
    fun provideInt(): Pair<KClass<out Number>, () -> Number> = Int::class to { 1 }

    @Provides
    @IntoMap
    fun provideDouble(): Pair<KClass<out Number>, () -> Number> = Double::class to { 1.0 }

    val numbersDelayed: Map<KClass<out Number>, () -> Number>
}
```

The reason this isn't supported is because the key and value are created together at runtime, if you were to try to write out an implementation of `numbersLazy` or `numbersDelayed` this should be more obvious 😉.

Dagger does this by creating keys through annotations instead, I chose not to go that route because it saves quite a bit of annotation machinery that was just dedicated to multi-bind keys.

**Comment by vRallev** [comment]
Your suggestion works, thanks!

> I chose not to go that route because it saves quite a bit of annotation machinery that was just dedicated to multi-bind keys.

Understandable, but this decision causes quite some boilerplate, too. Personally speaking, coming from Dagger and Anvil (I'm the Anvil author), needing to rely on typealiases as qualifier alternative is tedious. In my past projects we often had a qualifier like `@ForScope(AppScope::class)` that we shared for several types. Now I need to create a qualifier for each type times each scope. 

But that's a separate discussion. This library is lovely in the KMP world!

**Comment by evant** [comment]
Yeah feel free to follow https://github.com/evant/kotlin-inject/issues/253 for that
