### ISSUE TITLE
Cannot scope child components dependencies with parent component's scope using Provides

### ISSUE THREAD

**Issue by devanshu6445** [evant/kotlin-inject#344]
I have a singleton component 
```
@Scope
annotation class Singleton

@Component
@Singleton
abstract class SingletonComponent {
    companion object {
        private var instance: SingletonComponent? = null

        /**
         * Get a singleton instance of [SingletonComponent].
         */
        fun getInstance() = instance ?: SingletonComponent::class.create(
        ).also { instance = it }
    }
}
```
and 
```
@Component
abstract class CoreDataLayerComponent(
    @Component val singletonComponent: SingletonComponent
) : StockMeHttpClientProvider {

    abstract val httpClient: HttpClient

    companion object {
        fun create() = CoreDataLayerComponent::class.create(
            SingletonComponent.getInstance()
        )
    }
}

interface StockMeHttpClientProvider {

    @Singleton
    @Provides
    fun provideStockMeHttpClient(): HttpClient = HttpClient {
        /**Code**/
    }
}
```
in different module, now i am trying to scope my Provides Dependency to ```Singleton``` scope but getting error
```@Provides with scope: `in`.stock.core.di.Singleton cannot be provided in an unscoped component```

I am able to scope the dependencies to parent component i.e Singleton scope when they are not created by ```@Provides```

**Comment by evant** [comment]
That error is expected, you can only used scoped provides in a component that's scopped in the same scope, in your example, you should move `: StockMeHttpClientProvider` to `SingletonComponent`

**Comment by devanshu6445** [comment]
@evant But i am creating a SingletonComponent so that i can scope any dependency to be singleton and SingletonComponent exists in a lower level module and why is it possible to only scope non ```Provides``` dependencies to parent Component?

**Comment by evant** [comment]
`@Provides` means 'this component is creating the dependency', if it's scoped the component has to have the same scope to make sure it has the correct lifetime. You could re-recreate `CoreDataLayerComponent` multiple times and you'd want your singleton to live longer than that, so it can't be the owner.

**Comment by evant** [comment]
Current recommendation for this is put a SingletonComponent interface in your base module and an impl of it in your app.

**Comment by devanshu6445** [comment]
@evant I tried it but getting the ```@Provides with scope: `in`.stock.core.di.ApplicationScope cannot be provided in an unscoped component```. Is it possible in future  tohave something where dependencies can be marked with ```@Provides``` outside of component like ```Hilt```
