### ISSUE TITLE
Interface Bindings

### ISSUE THREAD

**Issue by jamesalee213** [evant/kotlin-inject#367]
Looking at the documentation, it looks like the only way to bind an interface type with a concrete class type is to write `@Provides` method in the `@Component`.

for example,
```kotlin
protected val RealHttp.bind: Http
    @Provides get() = this
```
or 
```kotlin
@Provides
fun http(http: RealHttp): Http = http
```

### proposed Enhancement
is it possible to provide a simpler way to do this when annotating the class? 
so that we don't have to add `@Provides` methods for these bindings? 
e.g.:
```kotlin
@Inject(boundType = Http::class)
class RealHttp : Http
```
or
```kotlin
@Inject @BindAs(Http::class)
class RealHttp : Http
```

**Comment by evant** [comment]
This looks like the same as https://github.com/evant/kotlin-inject/issues/212

**Comment by jamesalee213** [comment]
> This looks like the same as https://github.com/evant/kotlin-inject/issues/212

@evant it looks like that issue has been open for awhile. 

I read the whole thread, but I'm not entirely sure what the course of action is from that issue. 
were you ok with the addition of:
* kotlin-inject-extensions` - could contain things like mentioned `ContributesMultibinding` as well as `ContributesBinding` (for like Anvil for kotlin-inject)

but no one has implemented it yet?

**Comment by evant** [comment]
Correct, I'm open to contributions and otherwise helping make sure components can be extended for these kind of things, but it's not a priority for me to implement myself.
