### ISSUE TITLE
Can't inject provided dependency into java class

### ISSUE THREAD

**Issue by sergeshustoff** [evant/kotlin-inject#401]
Problem:
when there is a java class in dependency graph we have to create `@Provides` function in component in order to inject it - having `@Inject` annotation on that's java class' constructor doesn't work.

I'm not sure if it's ksp limitation or not, will need to research that...

**Comment by evant** [comment]
It should work in theory, there's even a test for it here, https://github.com/evant/kotlin-inject/blob/main/integration-tests/common-jvm/src/test/kotlin/me/tatarka/inject/test/JavaTest.kt, but it's possible there may be an issue with it, any chance you can create a sample the reproduces?

**Comment by sergeshustoff** [comment]
Looks like my complicated setup breaks in some corner case. I'll try find a simple case to reproduce it

**Comment by sergeshustoff** [comment]
[failing_provided_injection_in_java_class.patch](https://github.com/user-attachments/files/15912346/failing_provided_injection_in_java_class.patch)
Ok, here is a path to make test fail. Looks like anything `@Provided` in component doesn't get injected into java constructor

**Comment by sergeshustoff** [comment]
Looks like the problem is in nullability. All java class arguments are considered nullable and library doesn't automatically inject provided non-nullable as nullable dependency

**Comment by sergeshustoff** [comment]
Though there is a strange difference in behaviour for thinkgs provided by inject constructor and provided explicidly

                    // java code
                    public class JavaIFoo  {

                        private final Foo foo;

                        @Inject
                        public JavaIFoo(Foo foo) {
                            this.foo = foo;
                        }

                        public Foo getFoo() {
                            return foo;
                        }
                    }
                    
                    // kotlin code
                    @Inject 
                    class Foo

                    @Component
                    abstract class JavaProvidedDependencyComponent {
                        abstract val javaFoo: JavaIFoo
                        
                    // @Provides fun foo() = Foo
                    }
                    
 It works like this, but if `@Inject` is commented on Foo and @Provides is uncommented - it stops working. I'm not sure anymore what the behavioud should be
