### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by ursusursus** [evant/kotlin-inject#430]
Hi, I'm evaluating this library to migrate away from dagger (+anvil) to allow for KMP.

But, It's still pre 1.0 and there's been no commits for 2 months.

Could you please provide your plans, or was this project abandoned (hope not)?

Thank you

**Comment by evant** [comment]
Not abandoned, not sure what kind of plans you are asking for?

**Comment by ursusursus** [comment]
Mostly asking about the activity, since it's been 3months since the last release - or rather, what all is missing to hit 1.0.0

**Comment by evant** [comment]
Good question! The reason it's not 1.0 currently is to allow some level of breaking changes. I haven't sat down to decide what is exactly needed as 1.0. https://github.com/evant/kotlin-inject/issues/253 would be the biggest blocker, but there might be some smaller edge-cases that may need to be worked out.

**Comment by evant** [comment]
https://github.com/evant/kotlin-inject/issues/417 is also possibly a blocker for 1.0 as it may require a change to the runtime library

**Comment by evant** [comment]
Create a [1.0 milestone](https://github.com/evant/kotlin-inject/milestone/4) to track issues that would need to be resolved before then. That should be enough info to close this but feel free to reply if you have any more questions!
