### ISSUE TITLE
Feature Request: Support Provider-like API for Instance Creation

### ISSUE THREAD

**Issue by leinardi** [evant/kotlin-inject#457]
Use `Provider<T>` to enable flexible and explicit creation of new instances of a dependency directly within the injection target. This avoids boilerplate factory definitions in the component and allows injection targets to control when and how many instances of a dependency are created.

Currently, kotlin-inject supports creating new instances through factory methods in `@Component` but, as far as I know, there is no built-in equivalent for a `Provider<T>`-like API directly available in injection targets.

---

#### Proposed Solution

Introduce a `Provider<T>`-like interface into kotlin-inject that can be injected into classes. This would allow injection targets to request new instances of a dependency explicitly and on demand. 

The proposed interface:

```kotlin
interface Provider<T> {
    fun get(): T
}
```

The kotlin-inject compiler would generate providers automatically for any class or dependency annotated with `@Inject`. The `Provider<T>` would invoke the binding logic for `T` each time `get()` is called.

---

#### Example: New Instance Creation in Injection Target

Here’s an example adapted to kotlin-inject:

##### Target Class

```kotlin
import me.tatarka.inject.annotations.Inject

@Inject
class BigCoffeeMaker(private val filterProvider: Provider<Filter>) {
    fun brew(numberOfPots: Int) {
        repeat(numberOfPots) {
            val filter = filterProvider.get() // New filter instance every time
            // Use the filter
        }
    }
}
```

##### Filter Class

```kotlin
@Inject
class Filter {
    // Implementation of Filter
}
```

##### AppComponent

```kotlin
@Component
abstract class AppComponent {
    abstract val bigCoffeeMaker: BigCoffeeMaker
}
```

##### Main Function

```kotlin
fun main() {
    val appComponent = AppComponent::class.create()
    val coffeeMaker = appComponent.bigCoffeeMaker
    coffeeMaker.brew(5)
}
```

---

#### Benefits
Eliminates the need for repetitive factory definitions in components or manual object creation in injection targets.

**Comment by leinardi** [comment]
Mmm, maybe this feature request is not necessary, am I wrong or I can just create a new instance using a lambda?
```kotlin
class BigCoffeeMaker(private val filterProvider: () -> Filter) {
}
```

**Comment by evant** [comment]
Yes you can use a lamda.

**Comment by leinardi** [comment]
Nice, is this documented anywhere? I thought it was a missing feature because I couldn't find how to do it

**Comment by evant** [comment]
It's under https://github.com/evant/kotlin-inject?tab=readme-ov-file#function-support--assisted-injection

I do understand the documentation can be improved, feel free to add your feedback to https://github.com/evant/kotlin-inject/issues/389

**Comment by leinardi** [comment]
Sure, done: https://github.com/evant/kotlin-inject/issues/389#issuecomment-2513871097
