### ISSUE TITLE
Support javax.inject

### ISSUE THREAD

**Issue by evant** [evant/kotlin-inject#9]
This would make it easier to migrate existing code.

**Comment by evant** [comment]
Support `@Qualifier`? Probably.

**Comment by DHosseiny** [comment]
Can javax.inject annotations be used in KMM shared library?

**Comment by evant** [comment]
The processor doesn't care what the target is, but javax.inject is a java library so you would need to create some porting or binding of it. Haven't tried but I don't see why it wouldn't work.

**Comment by DHosseiny** [comment]
As javax.inject is a java library when I import javax.Inject annotation in a kotlin file in multiplatform module it is unknown.
